type Query {
    saveCharacter(characterDAO: inputCharacterDAO): CharacterDAO
    charactersByUserId(userId: String): [CharacterObject]
    characterById(characterId: String): CharacterDAO
    fullCharacterById(characterId: String): CharacterDAO
    createInventoryItem(inventoryItem: inputInventory): InventoryDAO
    getCharacterInventory(characterId: String): [InventoryDAO]
    getCharacterInventoryByType(characterId: String, itemType: String): [InventoryDAO]
    getItemListByType(itemType: String): [Item]
    getWeaponList: [Item]
    getTalentsList: [String]
    getAncestryList(source: String): [Ancestry]
    getTraitsList(type: String): [Trait]
    getBackgroundList(source: String): [Background]
    getBackgroundScreen(source:String): BackgroundDAO
    getProficiencyNames(proficiencies: String): [ProficiencyDAO]
    getTalentAndAttributeData(talent1Name: String, talent2Name: String): [TalentDAO]
    calculateState(state: inputCharacterState, character: inputCharacterObject): CalculatedState
    getCharacterStateById(id: String): CharacterState
    getAllSpells: [Spell]
    createGame(ownerId: String): Game
    saveGame(game: inputGame): Game
    getGameById(gameId:String): GameDAO
    createSpellCharacter(characterId: String, spellId: String): SpellCharacter
}

type Mutation {
    addEffect(effectName: String, state: inputCharacterState): CharacterDAO
    addCharactersToGame(gameId:String, characterId: String): Game
    changeGameOwner(gameId: String, userId: String): Game
    RemoveCharacterFromGame(gameId: String, characterId: String): GameDAO
    modifyPartyInventoryItem(inventoryItem: inputPartyInventory): PartyInventory
    saveSpellCharacter(characterSpells: [inputSpellCharacter]): Int 
    changeItemOwner(inventoryItem: inputInventory, newOwnerId: String, transferQuantity: Int): Int
}

type CharacterObject {
    id: String
    userId: String
    name: String
    attributeLevel: Int
    attribute1: Int
    attribute2: Int
    talent1: String
    talent2: String
    size: String
    ancestry: String
    background: String
    baseFitness: Int
    basePrecision: Int
    baseFocus: Int
    baseSense: Int
    proficiencies: String
}

input inputCharacterObject {
    id: String
    userId: String
    name: String
    attributeLevel: Int
    attribute1: Int
    attribute2: Int
    talent1: String
    talent2: String
    size: String
    background: String
    ancestry: String
    baseFitness: Int
    basePrecision: Int
    baseFocus: Int
    baseSense: Int
    proficiencies: String
}

type CharacterState {
    id: String
    characterId: String
    hitPoints: Int
    armor: Int
    manaPoints: Int
    activeEffects: String
    inactiveEffects: String
}

input inputCharacterState {
    id: String
    characterId: String
    hitPoints: Int
    armor: Int
    manaPoints: Int
    activeEffects: String
    inactiveEffects: String
}

type CalculatedState {
    characterId: String 
    hitPointsMax: Int
    hitPoints: Int
    armorMax: Int
    armorMin: Int
    armor: Int
    manaMax: Int
    manaPoints: Int
    spellCapacity: Int
    dexterity: Int
    celerity: Int
    awareness: Int
    subtlety: Int
    evasion: Int
    tenacity: Int
    encumbrance: Int
    fitness: Int
    precision: Int
    focus: Int
    sense: Int
    woundsMax: Int
    wounds: Int
    movement: Int
}

type Spell {
    id: String
    name: String
    spellType: String
    source: String
    actionCost: String
    manaCost: Int
    range: String
    duration: String
    description: String
    effectAmount: String
    effectConditional: String
    effectType: String
    tags: String
}

input inputSpell {
    id: String
    name: String
    spellType: String
    source: String
    actionCost: String
    manaCost: Int
    range: String
    duration: String
    description: String
    effectAmount: String
    effectConditional: String
    effectType: String
    tags: String
}

type SpellCharacter {
    id: String
    characterId: String
    spellId: String
}

input inputSpellCharacter {
    id: String
    characterId: String
    spellId: String
}

type Inventory {
    id: String
    characterId: String
    itemId: String
    equipped: Boolean
    proficiency: Int
    quantity: Int
}

input inputInventory {
    id: String
    characterId: String
    itemId: String
    equipped: Boolean
    quantity: Int
}

type Item {
    id: String
    name: String
    itemType: String
    subtype: String
    equippable: Boolean
    size: String
    weight: Float
    description: String
    properties: String
    attack1String: String
    attack2String: String
    effectName: String
    baseCost: Int
    rarity: String
}

input inputItem {
    id: String
    name: String
    itemType: String
    subtype: String
    equippable: Boolean
    size: String
    weight: Float
    description: String
    properties: String
    attack1String: String
    attack2String: String
    effectName: String
    baseCost: Int
    rarity: String
}

type Effect {
    id: String
    name: String
    description: String
    charProperty: String
    effectType: Int
    conditionalCheck: String
    effect: String
}

type Attribute {
    id: String
    name: String
    talentName: String
    flag: Int
    description: String
}

type Ancestry {
    id: String
    name: String
    parent: String
    source: String
    trait1: String
    trait2: String
    size: String
    description: String
}

type Trait {
    id: String
    name: String
    traitType: String
    description: String
    tags: String
}

type Background {
    id: String
    name: String
    source: String
    parentTrait: String
    childTrait: String
    deity: String
    description: String
    tags: String
}

type Talent {
    id: String
    name: String
    ability1: String
    ability2: String
    description: String
    hpBonus: Int
    prioritySkills: String
    role: String
    complexity: Int
    keystone: String
    capstone: String
    caster: Boolean
}

type Game {
    id: String
    ownerId: String
    characterIds: String
    playerIds: String
    joinCode: String
}

input inputGame {
    id: String
    ownerId: String
    characterIds: String
    playerIds: String
    joinCode: String
}

type PartyInventory {
    id: String
    gameId: String
    itemId: String
    location: String
}

input inputPartyInventory {
    id: String
    gameId: String
    itemId: String
    location: String
}

type GameDAO {
    game: Game
    characters: [CharacterObject]
    partyInventory: [PartyInventory]
}

type CharacterDAO {
    inventory: [InventoryDAO]
    character: CharacterObject
    attributes: [Attribute]
    talents: [Talent]
    proficiencies: [ProficiencyDAO]
    characterState: CharacterState
    calculatedState: CalculatedState
    spells: [SpellCharacter]
    traitData: TraitDAO
}

input inputCharacterDAO {
    inventory: [inputInventoryDAO]
    character: inputCharacterObject
    characterState: inputCharacterState
    spells: [inputSpellCharacter]
}

type ProficiencyDAO {
    item: Item
    mastery: Boolean
}

type TalentDAO { 
    talent: Talent
    attributes: [Attribute]
}

type SpellDAO{
    spell: Spell
    SpellCharacter: SpellCharacter
}

input inputSpellDAO{
    spell: inputSpell
    SpellCharacter: inputSpellCharacter
}

type InventoryDAO {
    inventory: Inventory
    item: Item
}

input inputInventoryDAO {
    inventory: inputInventory
    item: inputItem
}

type TraitDAO {
    ancestry: Ancestry
    background: Background
    traits: [Trait]
}

type BackgroundDAO {
    ancestries: [Ancestry]
    backgrounds: [Background]
    traits: [Trait]
}
