type Query {
    createOrFindCharacter(character: inputCharacterObject): CharacterObject
    charactersByUserId(userId: String): [CharacterObject]
}

type CharacterObject {
    id: String
    userId: String
    name: String
    aspectLevel: Int
    aspects1: Int
    aspects2: Int
    specialty1: Int
    specialty2: Int
    ancestryTrait: Int
    ancestryName: String
    baseFitness: Int
    baseTechnique: Int
    baseFocus: Int
    baseSense: Int
    gold: Int
    silver: Int
    copper: Int
}

input inputCharacterObject {
    id: String
    userId: String
    name: String
    aspectLevel: Int
    aspects1: Int
    aspects2: Int
    specialty1: Int
    specialty2: Int
    ancestryTrait: Int
    ancestryName: String
    baseFitness: Int
    baseTechnique: Int
    baseFocus: Int
    baseSense: Int
    gold: Int
    silver: Int
    copper: Int
}