spring.application.name=Spellblade-backend
spring.graphql.graphiql.enabled=true
spring.data.mongodb.uri=mongodb+srv://spellbladettrpg_db_user:vxZraFARoiYTnPxx@spellblade0.mongodb.net/SPELLBLADE_DEV
spring.data.mongodb.database=SPELLBLADE_DEV
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/spellblade.pfx
server.ssl.key-store-password=WAluigi#1
server.ssl.key-alias=spellblade
trust.store=classpath:keystore/spellblade.pfx
trust.store.password=WAluigi#1
spring.data.mongodb.auto-index-creation=true
server.port=8443